In [1]:
#array
import numpy as np
list=np.array(['A','B','C','D'])
print(list)

['A' 'B' 'C' 'D']


In [2]:
#integer
import numpy as np
list=np.array([1,2,3,4,5,6,7])
print(list[-1])
print(list[-2])
print(list[-3])

7
6
5


In [3]:
#float
import numpy as np
list=np.array([1.2,4.5,3.4,66.7])
print(list[-1])

66.7


In [4]:
#complex
import numpy as np
a=np.array([5+3j])
b=np.array([5+7j])
print(a+b)

[10.+10.j]


In [5]:
#boolean
import numpy as np
a=np.array([24])
print(bool(a))

True


# numpy methods

In [6]:
#Append
import numpy as np
a=np.array([1,2,3,4])
b=np.append(a,5)
print(b)

[1 2 3 4 5]


In [7]:
#insert
import numpy as np
list1=np.array(["mobile","instagram","reels"])
list2=np.insert(list1,1,"app")
print(list2)

['mobile' 'app' 'instagram' 'reels']


In [8]:
#delete
import numpy as np
a=np.array(["town","hospital","library"])
b=np.delete(a,2)
print(b)

['town' 'hospital']


In [9]:
#copy
import numpy as np
a=np.array([1,2,3,4,5])
b=np.copy(a)
print(b)

[1 2 3 4 5]


In [10]:
#sort
import numpy as np
a=np.array([4,5,6,1,2,3,7,8])
b=np.sort(a)
print(b)

[1 2 3 4 5 6 7 8]


In [11]:
#reverse
import numpy as np
a=np.array([9,8,7,6,5,4,3,2,1])
b=a[::-1]
print(b)

[1 2 3 4 5 6 7 8 9]


In [12]:
#unique
import numpy as np
a=np.array([1,2,3,1,2,3,4,3,2,3,3,2,3,7,8])
b=np.unique(a)
print(b)

[1 2 3 4 7 8]


In [13]:
#size
import numpy as np
a=np.array([1,2,3,4])
b=np.size(a)
print(b)

4


In [14]:
#clear
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([])
print(b)

[]


In [15]:
#SUM, MEAN, MAX, MIN
arr = np.array([1, 2, 3, 4, 5])
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())

Sum: 15
Mean: 3.0
Max: 5
Min: 1


In [18]:
#extend
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.append(a,b)
print(c)

[1 2 3 4 5 6 7 8]
