In [3]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)                                                

0
1
2
3


In [2]:
#array
import numpy as np
list=np.array(['A','B','C','D'])
print(list)

['A' 'B' 'C' 'D']


In [4]:
#integer
import numpy as np
list=np.array([1,2,3,4,5,6,7])
print(list[-1])
print(list[-2])
print(list[-3])

7
6
5


In [2]:
#float
import numpy as np
list=np.array([1.2,4.5,3.4,66.7])
print(list[-1])

66.7


In [6]:
#complex
import numpy as np
a=np.array([5+3j])
b=np.array([5+7j])
print(a+b)

[10.+10.j]


In [8]:
#boolean
import numpy as np
a=np.array([24])
print(bool(a))

True


In [9]:
import numpy as np
list_1=[1,2,3,4]
sample_array=np.array(list)
print("List in python:",list)
print("numpy Array in Python:",sample_array)

List in python: [ 1.2  4.5  3.4 66.7]
numpy Array in Python: [ 1.2  4.5  3.4 66.7]


# joining numpy arrays

In [2]:
#join two arrays
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [4]:
#join two 2-d array(axis=1)
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
#hsatck
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [6]:
#vstack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#dstack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [8]:
#sort the array
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [9]:
#alphabetically
import numpy as np
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [10]:
#decending
import numpy as np
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr)[::-1])

['cherry' 'banana' 'apple']


In [1]:
#Array dimensions
import numpy as np
a = np.array([1, 2, 3])          # 1D
b = np.array([[1, 2], [3, 4]])   # 2D
c = np.array([[[1,2],[3,4]]])    # 3D
print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)


(2, 2)
4
2
int32


In [2]:
#Data types
import numpy as np
arr = np.array([1, 2, 3], dtype=float)# allows float,int,complex,bool,str
print(arr)

[1. 2. 3.]


In [13]:
#Array creation method
import numpy as np

# 1. np.array() – Create array from list
arr1 = np.array([1, 2, 3, 4, 5])
print("np.array():\n", arr1)

# 2. np.zeros() – Array of zeros
arr2 = np.zeros((3, 3),dtype=int)
print("\nnp.zeros():\n", arr2)

# 3. np.ones() – Array of ones
arr3 = np.ones((2, 4),dtype=int)
print("\nnp.ones():\n", arr3)

# 4. np.full() – Array with constant value
arr4 = np.full((3, 3), 7)
print("\nnp.full():\n", arr4)

# 5. np.eye() – Identity matrix
arr5 = np.eye((4),dtype=int)
print("\nnp.eye():\n", arr5)

# 6. np.arange() – Range of values
arr6 = np.arange(10, 51, 5)
print("\nnp.arange():\n", arr6)

# 7. np.linspace() – Evenly spaced values
arr7 = np.linspace(0, 1, 6)
print("\nnp.linspace():\n", arr7)

# 8. np.random.rand() – Random floats (0 to 1)
arr8 = np.random.rand(3, 3)
print("\nnp.random.rand():\n", arr8)

# 9. np.random.randint() – Random integers
arr9 = np.random.randint(1, 100, 5)
print("\nnp.random.randint():\n", arr9)

# 10. np.empty() – Uninitialized array
arr10 = np.empty((2, 2))
print("\nnp.empty():\n", arr10)


np.array():
 [1 2 3 4 5]

np.zeros():
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

np.ones():
 [[1 1 1 1]
 [1 1 1 1]]

np.full():
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

np.eye():
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

np.arange():
 [10 15 20 25 30 35 40 45 50]

np.linspace():
 [0.  0.2 0.4 0.6 0.8 1. ]

np.random.rand():
 [[0.26192687 0.72515477 0.53932699]
 [0.18733729 0.47576471 0.50453139]
 [0.51225521 0.42594063 0.34499973]]

np.random.randint():
 [34 40 76 73 40]

np.empty():
 [[2.12199579e-314 2.12199579e-314]
 [2.12199579e-314 2.12199579e-314]]


In [14]:
#Indexing & Slicing
arr = np.array([10, 20, 30, 40])
print(arr[1])        # 20
print(arr[1:3])      # [20 30]


20
[20 30]


In [15]:
#1d array indexing
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    # First element
print(arr[-1])   # Last element


10
50


In [16]:
#2D Array Indexing
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print(mat[0, 1])   # Row 0, Column 1 → 2
print(mat[1, 2])

2
6


In [17]:
#1D Array Slicing
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])     # [20 30 40]
print(arr[:3])      # [10 20 30]
print(arr[::2])   

[20 30 40]
[10 20 30]
[10 30 50]


In [18]:
#2D Array Slicing
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0:2, 1:3])

[[2 3]
 [5 6]]


In [22]:
#3. Modifying Using Indexing & Slicing
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 99
print(arr)

mat = np.array([[1,2,3],[4,5,6]])
mat[:, 1] = 0
print(mat)


[ 1  2 99  4  5]
[[1 0 3]
 [4 0 6]]


In [23]:
#🔹 4. Boolean Indexing ⭐ (Very Important)
#Condition-Based Selection
arr = np.array([10, 5, 20, 3, 15])

print(arr[arr > 10])

#Modify Using Condition
arr[arr < 10] = 0
print(arr)

[20 15]
[10  0 20  0 15]


In [24]:
#5. Fancy Indexing (Multiple Indexes)
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])

[10 30 50]


In [25]:
#6. Copy vs View (Exam Favorite)
#View (Changes affect original)
a = np.array([1, 2, 3, 4])
b = a[1:3]
b[:] = 99

print(a)

[ 1 99 99  4]


In [26]:
#Copy (Independent array)
a = np.array([1, 2, 3, 4])
b = a[1:3].copy()
b[:] = 99

print(a)

[1 2 3 4]


In [27]:
a = [1, 2, 3, 4]
b = []

for i in a:
    b.append(i * 2)

print(b)


[2, 4, 6, 8]


In [28]:
#Using NumPy Vectorization
import numpy as np

a = np.array([1, 2, 3, 4])
b = a * 2
print(b)

[2 4 6 8]


In [29]:
#1. Arithmetic Operations
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [30]:
#2. Scalar Operations
arr = np.array([1, 2, 3, 4])

print(arr + 10)
print(arr * 5)

[11 12 13 14]
[ 5 10 15 20]


In [33]:
#3. Mathematical Functions
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [34]:
#4. Comparison Operations
arr = np.array([5, 10, 15, 20])

print(arr > 10)
print(arr == 15)

[False False  True  True]
[False False  True False]


In [35]:
#5. Boolean Vectorized Operations
arr = np.array([2, 7, 4, 9, 1])

print(arr[arr > 5])

[7 9]


In [36]:
#6. Conditional Vectorization (np.where)
arr = np.array([10, 3, 8, 1])

result = np.where(arr > 5, "High", "Low")
print(result)

['High' 'Low' 'High' 'Low']


In [37]:
#7. Vectorized Aggregations
arr = np.array([10, 20, 30, 40])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

100
25.0
40


In [38]:
#Vectorization in 2D Arrays
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print(mat * 2)
print(mat + 10)

[[ 2  4  6]
 [ 8 10 12]]
[[11 12 13]
 [14 15 16]]


In [39]:
#7. Broadcasting
#Allows operations between different shaped arrays.

arr = np.array([1,2,3])
print(arr + 10)

[11 12 13]


In [40]:
#Common Mathematical Functions (with Examples)
#1. Basic Arithmetic Functions
import numpy as np

a = np.array([10, 20, 30])

print(np.add(a, 5))
print(np.subtract(a, 5))
print(np.multiply(a, 2))
print(np.divide(a, 2))

[15 25 35]
[ 5 15 25]
[20 40 60]
[ 5. 10. 15.]


In [41]:
#2. Power & Root Functions
arr = np.array([1, 4, 9, 16])

print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr, 2))

[  1  16  81 256]
[1. 2. 3. 4.]
[  1  16  81 256]


In [42]:
#3. Exponential & Logarithmic Functions
arr = np.array([1, 2, 3])

print(np.exp(arr))
print(np.log(arr))      # Natural log
print(np.log10(arr))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


In [43]:
#4. Trigonometric Functions
#Values in radians)
angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [44]:
#5. Rounding Functions
arr = np.array([1.2, 2.5, 3.7])

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]


In [45]:
#6. Absolute & Sign Functions
arr = np.array([-10, -5, 0, 5, 10])

print(np.abs(arr))
print(np.sign(arr))

[10  5  0  5 10]
[-1 -1  0  1  1]


In [46]:
#7. Aggregate Mathematical Functions
arr = np.array([10, 20, 30, 40])

print(np.sum(arr))
print(np.prod(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

100
240000
25.0
40
10


In [47]:
#8. Cumulative Functions
arr = np.array([1, 2, 3, 4])

print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10]
[ 1  2  6 24]


In [48]:
#9. Difference & Gradient
arr = np.array([1, 4, 9, 16])

print(np.diff(arr))
print(np.gradient(arr))

[3 5 7]
[3. 4. 6. 7.]


In [49]:
#Mathematical Functions on 2D Arrays
mat = np.array([[1, 2],
                [3, 4]])

print(np.sum(mat))
print(np.sum(mat, axis=0))  # Column-wise
print(np.sum(mat, axis=1))  # Row-wise

10
[4 6]
[3 7]


In [51]:
#statistical functions
#1. Mean (np.mean)
#Average value of the data.
import numpy as np

arr = np.array([10, 20, 30, 40])
print(np.mean(arr))

25.0


In [52]:
#2. Median (np.median)
#Middle value after sorting.

arr = np.array([10, 30, 20, 40])
print(np.median(arr))

25.0


In [53]:
#3. Standard Deviation (np.std)
#Measures data spread from the mean.
arr = np.array([10, 20, 30, 40])
print(np.std(arr))

11.180339887498949


In [54]:
#4. Variance (np.var)
#Square of standard deviation.

print(np.var(arr))

125.0


In [55]:
#5. Minimum & Maximum
print(np.min(arr))
print(np.max(arr))

10
40


In [56]:
#6. Range (Max − Min)
data_range = np.max(arr) - np.min(arr)
print(data_range)

30


In [58]:
#7. Percentile (np.percentile)
#Value below which a given percentage of data lies.
arr = np.array([10, 20, 30, 40, 50])
print(np.percentile(arr, 50))

30.0


In [59]:
#8. Quantile (np.quantile)
print(np.quantile(arr, 0.25))
print(np.quantile(arr, 0.75))

20.0
40.0


In [60]:
#9. Sum & Product
print(np.sum(arr))
print(np.prod(arr))

150
12000000


In [62]:
#10. Argmin & Argmax
#Returns index of min/max value.
arr = np.array([10, 20, 30, 40, 50])
print(np.argmin(arr))
print(np.argmax(arr))

0
4


In [63]:
#Statistical Functions on 2D Arrays
mat = np.array([[10, 20, 30],
                [40, 50, 60]])

print(np.mean(mat))            # Overall mean
print(np.mean(mat, axis=0))    # Column-wise mean
print(np.mean(mat, axis=1))

35.0
[25. 35. 45.]
[20. 50.]


In [65]:
#11. Covariance (np.cov)
x = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])
print(np.cov(x, y))
#12. Correlation (np.corrcoef)
print(np.corrcoef(x, y))

[[1.66666667 3.33333333]
 [3.33333333 6.66666667]]
[[1. 1.]
 [1. 1.]]


In [66]:
#🔹 NaN-aware Statistical Functions ⭐
#Used when data has missing values.

arr = np.array([10, 20, np.nan, 40])

print(np.nanmean(arr))
print(np.nanstd(arr))

23.333333333333332
12.472191289246473


In [69]:
#Common Linear Algebra Functions
#1. Matrix Multiplication
import numpy as np
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.dot(A, B))
# OR
print(A @ B)
#2. Transpose
print(A.T)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [70]:
#3. Determinant
print(np.linalg.det(A))

-2.0000000000000004


In [71]:
#4. Inverse of a Matrix
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [72]:
#5. Eigenvalues & Eigenvectors
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [73]:
#6. Solving Linear Equations
#Solve:
#2x + y = 5 ,x + y = 3

coef = np.array([[2, 1],
                 [1, 1]])
const = np.array([5, 3])

solution = np.linalg.solve(coef, const)
print(solution)

[2. 1.]


In [76]:
#7. Rank of Matrix
import numpy as np
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
print(np.linalg.matrix_rank(A))

2


In [77]:
#8. Trace of Matrix
print(np.trace(A))

5


In [78]:
#1. Random Floats (0 to 1)
print(np.random.rand(3, 3))

[[0.04894198 0.16545675 0.26032567]
 [0.30535947 0.91585183 0.55467791]
 [0.96806952 0.44257951 0.55904032]]


In [79]:
#2. Random Integers
print(np.random.randint(1, 100, 5))

[82 24 77 69 42]


In [80]:
#3. Random Normal Distribution
print(np.random.randn(5))

[ 0.20345547 -0.2969996   0.18522861  0.19200742 -0.43854552]


In [81]:
#4. Random Choice
arr = np.array([10, 20, 30, 40])
print(np.random.choice(arr, 2))

[30 10]


In [82]:
#5. Random Shuffle
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[1 4 3 5 2]


In [83]:
#6. Random Seed (Reproducibility)
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [84]:
#7. Uniform Distribution
print(np.random.uniform(5, 10, 5))

[7.99329242 5.7800932  5.7799726  5.29041806 9.33088073]


In [85]:
#8. Normal Distribution (Mean, Std)
print(np.random.normal(50, 10, 5))

[65.79212816 57.67434729 45.30525614 55.42560044 45.36582307]


In [86]:
#🔹 Real-Time ML Example
weights = np.random.randn(3, 3)
print(weights)

[[-0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112]
 [ 0.31424733 -0.90802408 -1.4123037 ]]


In [87]:
#reshaping & Manipulation
#1. reshape()
#Changes the shape of an array without changing data.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)
#⚠ Total elements must match

[[1 2 3]
 [4 5 6]]


In [88]:
#2. flatten()
#Converts a multi-dimensional array into a 1D array (copy).

mat = np.array([[1, 2],
                [3, 4]])

flat = mat.flatten()
print(flat)
#✔ Returns a copy

[1 2 3 4]


In [91]:
#3. ravel()
#Flattens array into 1D view (if possible).
mat = np.array([[1, 2],
                [3, 4]])
ravel_arr = mat.ravel()
print(ravel_arr)
#✔ Faster than flatten()
#✔ Usually returns a view

[1 2 3 4]


In [92]:
#4. transpose() / .T
#Swaps rows and columns.
mat = np.array([[1, 2],
                [3, 4]])
print(mat.T)

[[1 3]
 [2 4]]


In [93]:
#5. resize()
#Changes shape in-place.
arr = np.array([1, 2, 3, 4])
arr.resize(2, 2)
print(arr)
#⚠ Modifies original array

[[1 2]
 [3 4]]


In [94]:
#6. expand_dims()
#Adds a new axis (dimension).

arr = np.array([1, 2, 3])

print(np.expand_dims(arr, axis=0))  # Row
print(np.expand_dims(arr, axis=1))  # Column

[[1 2 3]]
[[1]
 [2]
 [3]]


In [95]:
#7. squeeze()
#Removes dimensions of size 1.
arr = np.array([[[1, 2, 3]]])
print(arr.squeeze())

[1 2 3]


In [96]:
#8. concatenate()
#Joins arrays along an axis.

a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.concatenate((a, b), axis=0))


[[1 2]
 [3 4]]


In [99]:
#9. stack()
print(np.stack((a, b)))
#Other Stack Variants
print(np.vstack((a, b)))   # Vertical
print(np.hstack((a, b))) # Horizontal

[[[1 2]]

 [[3 4]]]
[[1 2]
 [3 4]]
[[1 2 3 4]]


In [100]:
#10. split()
#Splits an array into multiple parts.

arr = np.array([1, 2, 3, 4, 5, 6])

print(np.split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]
